### ISSUE TITLE
Passwords containing '@' do not work

### ISSUE THREAD

**Issue by h1uke** [diegonehab/luasocket#281] opened 2019-04-30 17:59 UTC
For example:
user=admin
password=PowerUser@123
host=camera.cctv
uri=/onvif-cgi/jpg/image.cgi

results to:
    url="http://admin:PowerUser@123@camera.cctv/onvif-cgi/jpg/image.cgi"
which cannot be parsed correctly.

A quick and dirty fix:

url.lua, Line 178:  
replace '`string.gsub(authority,"^([^@]*)@"`' to '`string.gsub(authority,"^(.*)@"`'

**Comment by diegonehab** [comment] 2019-05-15 02:20
Dirty indeed. You cannot have a @ character in an URL. It is a protected character. You need to escape it. then everything will work as intended. See "url.escape" and "url.unescape" in the URL module. Does this close the issue?

**Closed** 2019-05-26 13:58 UTC
