### ISSUE TITLE
socket tests indexed from global scope

### ISSUE THREAD

**Issue by jbbjarnason** [diegonehab/luasocket#297] opened 2020-03-20 09:20 UTC
I am unable to run for example this test: https://github.com/diegonehab/luasocket/blob/master/test/tcp-getoptions#L3

```bash
jonb@ubuntu:~/luasocket/test$ ./tcp-getoptions 
lua: ./tcp-getoptions:21: attempt to index global 'socket' (a nil value)
stack traceback:
	./tcp-getoptions:21: in main chunk
	[C]: ?
```

is luasocket supposed to be accessible from the global scope?

**Comment by ewestbrook** [comment] 2020-03-27 22:58
Bug confirmed.  Opened #299 with partial fix.  Work in progress.

**Comment by jbbjarnason** [comment] 2020-03-28 17:36
I checked the other tests and found 3 other cases:
https://github.com/diegonehab/luasocket/blob/master/test/udp-zero-length-send
https://github.com/diegonehab/luasocket/blob/master/test/udp-zero-length-send-recv
https://github.com/diegonehab/luasocket/blob/master/test/find-connect-limit

**Comment by ewestbrook** [comment] 2020-03-28 20:24
Testing after applying the above patch:

Linux:

```
$ ./test/tcp-getoptions
options for     tcp{master}: 0x55b0885ec428
getoption       keepalive       nil     getsockopt failed
getoption       reuseaddr       nil     getsockopt failed
getoption       tcp-nodelay     nil     getsockopt failed
getoption       tcp-keepidle    nil     getsockopt failed
getoption       tcp-keepcnt     nil     getsockopt failed
getoption       tcp-keepintvl   nil     getsockopt failed
lua: ./test/tcp-getoptions:17: attempt to index a nil value
stack traceback:
        ./test/tcp-getoptions:17: in function 'options'
        ./test/tcp-getoptions:23: in main chunk
        [C]: ?
```

macOS:

```
$ ./test/tcp-getoptions
options for     tcp{master}: 0x7fd235808228
getoption       keepalive       nil     getsockopt failed
getoption       reuseaddr       nil     getsockopt failed
getoption       tcp-nodelay     nil     getsockopt failed
lua: ./test/tcp-getoptions:13: bad argument #1 to 'getoption' (unsupported option `tcp-keepidle')
stack traceback:
        [C]: in function 'getoption'
        ./test/tcp-getoptions:13: in function 'options'
        ./test/tcp-getoptions:23: in main chunk
        [C]: ?
```

**Comment by ewestbrook** [comment] 2020-03-28 21:17
Added a commit to #299 with pcall() to guard for unsupported option or other errors.  Also added a test for return value of getoption"linger".

Results are now:

Linux:

```
$ ./test/tcp-getoptions
options for     tcp{master}: 0x5626a77558f8
getoption       keepalive       true    nil     getsockopt failed
getoption       reuseaddr       true    nil     getsockopt failed
getoption       tcp-nodelay     true    nil     getsockopt failed
getoption       tcp-keepidle    true    nil     getsockopt failed
getoption       tcp-keepcnt     true    nil     getsockopt failed
getoption       tcp-keepintvl   true    nil     getsockopt failed
getoption       linger  no result
options for     tcp{server}: 0x5626a77558f8
getoption       keepalive       true    false
getoption       reuseaddr       true    false
getoption       tcp-nodelay     true    false
getoption       tcp-keepidle    true    7200
getoption       tcp-keepcnt     true    9
getoption       tcp-keepintvl   true    75
getoption       linger  on      false   timeout 0
options for     tcp{server}: 0x5626a77579a8
getoption       keepalive       true    false
getoption       reuseaddr       true    true
getoption       tcp-nodelay     true    false
getoption       tcp-keepidle    true    7200
getoption       tcp-keepcnt     true    9
getoption       tcp-keepintvl   true    75
getoption       linger  on      false   timeout 0
options for     tcp{client}: 0x5626a7759a58
getoption       keepalive       true    false
getoption       reuseaddr       true    false
getoption       tcp-nodelay     true    false
getoption       tcp-keepidle    true    7200
getoption       tcp-keepcnt     true    9
getoption       tcp-keepintvl   true    75
getoption       linger  on      false   timeout 0
options for     tcp{client}: 0x5626a775bb08
getoption       keepalive       true    false
getoption       reuseaddr       true    true
getoption       tcp-nodelay     true    false
getoption       tcp-keepidle    true    7200
getoption       tcp-keepcnt     true    9
getoption       tcp-keepintvl   true    75
getoption       linger  on      false   timeout 0
```

macOS:

```
$ ./test/tcp-getoptions
options for     tcp{master}: 0x7f8a70805628
getoption       keepalive       true    nil     getsockopt failed
getoption       reuseaddr       true    nil     getsockopt failed
getoption       tcp-nodelay     true    nil     getsockopt failed
getoption       tcp-keepidle    fail: bad argument #2 to '?' (unsupported option `tcp-keepidle')
getoption       tcp-keepcnt     true    nil     getsockopt failed
getoption       tcp-keepintvl   true    nil     getsockopt failed
getoption       linger  no result
options for     tcp{server}: 0x7f8a70805628
getoption       keepalive       true    false
getoption       reuseaddr       true    false
getoption       tcp-nodelay     true    false
getoption       tcp-keepidle    fail: bad argument #2 to '?' (unsupported option `tcp-keepidle')
getoption       tcp-keepcnt     true    8
getoption       tcp-keepintvl   true    75
getoption       linger  on      false   timeout 0
options for     tcp{server}: 0x7f8a71002828
getoption       keepalive       true    false
getoption       reuseaddr       true    true
getoption       tcp-nodelay     true    false
getoption       tcp-keepidle    fail: bad argument #2 to '?' (unsupported option `tcp-keepidle')
getoption       tcp-keepcnt     true    8
getoption       tcp-keepintvl   true    75
getoption       linger  on      false   timeout 0
options for     tcp{client}: 0x7f8a71004a28
getoption       keepalive       true    false
getoption       reuseaddr       true    false
getoption       tcp-nodelay     true    false
getoption       tcp-keepidle    fail: bad argument #2 to '?' (unsupported option `tcp-keepidle')
getoption       tcp-keepcnt     true    8
getoption       tcp-keepintvl   true    75
getoption       linger  on      false   timeout 0
options for     tcp{client}: 0x7f8a70003e28
getoption       keepalive       true    false
getoption       reuseaddr       true    true
getoption       tcp-nodelay     true    false
getoption       tcp-keepidle    fail: bad argument #2 to '?' (unsupported option `tcp-keepidle')
getoption       tcp-keepcnt     true    8
getoption       tcp-keepintvl   true    75
getoption       linger  on      false   timeout 0
```

**Comment by ewestbrook** [comment] 2020-03-28 21:22
Added a fix to `test/udp-zero-length-send` to enable it to run.

**Comment by ewestbrook** [comment] 2020-03-28 21:25
Did the same for `test/udp-zero-length-send-recv`.  Results vary by platform:

Linux:

```
$ ./test/udp-zero-length-send-recv
ok
```

macOS:

```
$ ./test/udp-zero-length-send-recv
fail - receive of zero failed with:     nil     timeout
```

**Comment by ewestbrook** [comment] 2020-03-28 21:28
Did the same for `test/find-connect-limit`.

**Comment by ewestbrook** [comment] 2020-03-28 22:22
Closing because #299 has been merged and scripts now run.  Please feel free to re-open if further action is needed.

**Closed by ewestbrook** 2020-03-28 22:22 UTC
